### ISSUE TITLE
FreePBX no calls to Zammad

### ISSUE THREAD

**Issue by yuljk** [martinvonwittich/asterisk-zammad-cti-bridge#5]
Hi - I've successfully setup the integration service on my FreePBX server, however when calling the number for my agent, I don't see anything in Zammad.

All I can see from /var/log/messages is:-

Jun 18 18:27:01 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:01 +0100 [debug] got event: Registry
Jun 18 18:27:18 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:18 +0100 [debug] got event: PeerStatus
Jun 18 18:27:31 cassiopea systemd[1]: Removed slice User Slice of asterisk.
Jun 18 18:27:43 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:43 +0100 [debug] got event: PeerStatus
Jun 18 18:27:46 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:46 +0100 [debug] got event: Registry
Jun 18 18:27:53 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:53 +0100 [debug] got event: PeerStatus

So looks like it is communicating OK.

In Zammad I have enabled CTI (generic) and set my default caller ID to my CallerID in inbound routes, otherwise everything else is untouched.

I'm not using queues or anything fancy on the PBX, just an inbound route that goes to a ring group with my extensions.

Any help would be appreciated!

**Comment by martinvonwittich** [comment]
Sorry, I don't know FreePBX at all. `asterisk-zammad-cti-bridge` only supports [Asterisk queues](https://wiki.asterisk.org/wiki/display/AST/Building+Queues), ie. it expects the following events:

- QueueCallerJoin
- AgentConnect
- AgentComplete
- QueueCallerAbandon

"Ring group" doesn't sound like queues, so `asterisk-zammad-cti-bridge` won't work for your case.

**Comment by yuljk** [comment]
Thanks for the replies.  I have now setup my queue in Asterisk.  However I see the following from asterisk-zammad-cti-bridge

EV: error in callback (ignoring): Undefined subroutine &URL::Encode::PP::build_urlencoded called at /opt/asterisk-zammad-cti-bridge/asterisk-zammad-cti-bridge line 96.

I suspect this is because I don't have the required perl module installed.

However, I cannot find this module for CentOS 7

The EPEL repo appears to only support CentOS 8 https://centos.pkgs.org/8/epel-x86_64/perl-WWW-Form-UrlEncoded-0.26-3.el8.noarch.rpm.html

Any ideas how I can get this working with CentOS 7?

Many thanks


Edit:  So I have found what I believe to be the correct module for CentOS 7 https://centos.pkgs.org/7/openfusion-x86_64/perl-URL-Encode-0.03-1.of.el7.noarch.rpm.html

This is installed and I have modified asterisk-cti- bridge-service to reflect the module name 'use URL::Encode'

I also modified line 96 to 'URL::Encode::build_urlencoded($post)'

I get the same error.

**Comment by martinvonwittich** [comment]
> Any ideas how I can get this working with CentOS 7?

Try `cpan WWW::Form::UrlEncoded`. This should download the required package directly from CPAN and install it locally. That's less clean than installing a distribution package, but an easy fix when there is no distribution package available (and on Debian also necessary for `Asterisk::AMI` because Debian also doens't provide a package for that).

**Comment by yuljk** [comment]
Thanks @martinvonwittich all working beautifully now. Doh, need to learn more about installing perl modules!
